// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Ymp5kwsCXislH3ZibikGq3joB3JVykM',
    appId: '1:982960830351:web:ceadf09e0bda0ac85cbdfa',
    messagingSenderId: '982960830351',
    projectId: 'flash-chat-4cf12',
    authDomain: 'flash-chat-4cf12.firebaseapp.com',
    databaseURL: 'https://flash-chat-4cf12-default-rtdb.firebaseio.com',
    storageBucket: 'flash-chat-4cf12.firebasestorage.app',
    measurementId: 'G-HZBRRF17ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsvVIYxcdrI-QE8ue3d9hQML6VWFXgsow',
    appId: '1:982960830351:android:1eb58408402db1375cbdfa',
    messagingSenderId: '982960830351',
    projectId: 'flash-chat-4cf12',
    databaseURL: 'https://flash-chat-4cf12-default-rtdb.firebaseio.com',
    storageBucket: 'flash-chat-4cf12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPHbfGW0g-dz9B-8A2Cwazyk9PldKtyeo',
    appId: '1:982960830351:ios:fb055eba8b5606ea5cbdfa',
    messagingSenderId: '982960830351',
    projectId: 'flash-chat-4cf12',
    databaseURL: 'https://flash-chat-4cf12-default-rtdb.firebaseio.com',
    storageBucket: 'flash-chat-4cf12.firebasestorage.app',
    androidClientId: '982960830351-1io7t3mtr1i21t9p85ea0dm7r1gv3kov.apps.googleusercontent.com',
    iosClientId: '982960830351-cqdt8f76ef1ta9fh4g42m8q051kfjavh.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPHbfGW0g-dz9B-8A2Cwazyk9PldKtyeo',
    appId: '1:982960830351:ios:fb055eba8b5606ea5cbdfa',
    messagingSenderId: '982960830351',
    projectId: 'flash-chat-4cf12',
    databaseURL: 'https://flash-chat-4cf12-default-rtdb.firebaseio.com',
    storageBucket: 'flash-chat-4cf12.firebasestorage.app',
    androidClientId: '982960830351-1io7t3mtr1i21t9p85ea0dm7r1gv3kov.apps.googleusercontent.com',
    iosClientId: '982960830351-cqdt8f76ef1ta9fh4g42m8q051kfjavh.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9Ymp5kwsCXislH3ZibikGq3joB3JVykM',
    appId: '1:982960830351:web:f1dc7609c4ef2e595cbdfa',
    messagingSenderId: '982960830351',
    projectId: 'flash-chat-4cf12',
    authDomain: 'flash-chat-4cf12.firebaseapp.com',
    databaseURL: 'https://flash-chat-4cf12-default-rtdb.firebaseio.com',
    storageBucket: 'flash-chat-4cf12.firebasestorage.app',
    measurementId: 'G-5SZCTVF61T',
  );
}
