name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'  # متوافقة مع Dart 3.8.1

      - name: Install dependencies
        run: flutter pub get

      - name: Build IPA
        run: flutter build ipa --release

      - name: Upload IPA
        uses: actions/upload-artifact@v4  # استخدم v4 بدل v3 عشان القديم اتوقف
        with:
          name: Kutuku-iOS
          path: build/ios/ipa/*.ipa
