name: Build and Release iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'
          cache: true

      - name: 3. Add GoogleService-Info.plist from Secret
        env:
          GOOGLE_SERVICE_PLIST_BASE64: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST_BASE64 }}
        run: |
          echo "Creating GoogleService-Info.plist..."
          if [ -z "$GOOGLE_SERVICE_PLIST_BASE64" ]; then
            echo "ERROR: GOOGLE_SERVICE_INFO_PLIST_BASE64 secret is not set."
            exit 1
          else
            echo $GOOGLE_SERVICE_PLIST_BASE64 | base64 --decode > $GITHUB_WORKSPACE/ios/Runner/GoogleService-Info.plist
            echo "GoogleService-Info.plist created successfully."
          fi

      # ===== الخطوة الجديدة والمهمة =====
      # هذه الخطوة تضمن إعادة بناء ملفات المشروع الأصلية بشكل سليم
      - name: 4. Restore/Generate Native Project Files
        run: flutter create .

      # هذه الخطوة مهمة لجلب الإضافات بعد التأكد من سلامة الملفات
      - name: 5. Get Flutter Dependencies
        run: flutter pub get

      - name: 6. Build IPA
        run: flutter build ipa --release --no-codesign

      - name: 7. Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-ipa
          path: build/ios/ipa/*.ipa